[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lottery_program = "5zu5FDmWzVxEtDcFefPGPrHVj363JWzLTghGD7mRRRTd"

[programs.devnet]
lottery_program = "5zu5FDmWzVxEtDcFefPGPrHVj363JWzLTghGD7mRRRTd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "SrunNkgXdSWerx9e51pVgFCtKJ3EoCskEkSoTquXHX7.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
